[package]
name = "survicraft-client"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
lightyear.workspace = true
survicraft-protocol = { path = "../survicraft-protocol" }
survicraft-render = { path = "../survicraft-render" }

[lints]
workspace = true
