[package]
name = "survicraft-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
leafwing-input-manager.workspace = true
lightyear.workspace = true
serde.workspace = true
rand.workspace = true

[lints]
workspace = true
